environments:
  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 0
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 1
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 2
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    image: dabstep:latest
    dataset: ""
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 3
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 4
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 5
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 6
      num_shards: 8
      max_steps: 10
      timeout: 60

  - env_name: dabstepgym
    env_num: 1
    dataset: ""
    image: dabstep:latest
    env_params:
      data_dir: "env/dabstep/data"
      artifacts_dir: "env/dabstep/artifacts"
      split: "dev"
      limit: 1
      shard_index: 7
      num_shards: 8
      max_steps: 10
      timeout: 60
