environments:
  - env_name: os_gym
    env_image: registry.h.pjlab.org.cn/ailab-evobox-evobox_cpu/os-gym:v0.2.0
    env_num: 1
    dataset: /mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/datasets/standard/osworld_cases_latest.jsonl  # JSONL dataset file with task configurations
    env_params:
      eval_mode: standard  # "standard" or "safety"
      provider_name: "docker"
      vm_path: "/mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/projects/AIEvoBox/env/osgym/docker_vm_data/Ubuntu.qcow2"
      capture_observation_type: screenshot_a11y_tree # Controls what the environment collects
      prompt_observation_type: screenshot # Controls what is fed into the model prompt
      headless: true
      action_space: "pyautogui"
      prompt_format: kimi
      screen_width: 1920
      screen_height: 1080
      cache_dir: "/tmp/osgym_cache"
      result_dir: /mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/standard_results_v1.4/osgym_kimi-k2.5_standard_osworld_cases_latest_rollout_1  # Relative to env/osgym directory
      save_screenshots: true
      sleep_after_execution: 2.0
      max_steps: 30
      enable_recording: false
      # LLM Judge configuration
      llm_judge_config:
        api_key: "sk-XYdTnAfyDo2QFMUaXTOutUxCu2reNXsIXiTMcd2oJZGMOHeR"
        base_url: "http://s-20260204175507-cqflp-decode.ailab-pj.svc:8000/v1/"
        model: "kimi-k2.5"
