mode: remote

database:
  driver: "sqlite"
  sqlite_path: "AIEvoBox/test_envs.db"    # Change this to your actual DB path

pool_size: 2

cluster:
  base_image: "AAAA" # TODO the base image should be deleted, we will have distinguished image for each env
  http:                    #shared, all the env services export the same port for connection
    port: 36663
    timeout_s: 100         # Connection timeouts from manager to env clusters
    concurrency: 200       # Max concurrent HTTP calls from manager when prewarming actors
    startup_concurrency: 16  # Max concurrent cold starts / reset attempts during prewarm
  env_types:
    mc:
      quotagroup: "evobox_cpu_task"
      entrypoint: "python /app/app.py"
      limit: 1
    emb:
      quotagroup: "evobox_gpu"
      entrypoint: "bash run.sh"
      limit: 1
    os_gym:
      quotagroup: "evobox_proxy"
      entrypoint: "bash -lc 'cd /mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/projects/AIEvoBox && export PYTHONPATH=/mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/projects/AIEvoBox:$PYTHONPATHb && bash /mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/projects/scripts/run.sh'"
      volumes:
        - fsType: "mount.brainpp.cn/gpfs"
          endpoint: "gpfs://gpfs2/evobox-share-gpfs2"
          containerPath: "/mnt/shared-storage-gpfs2/evobox-share-gpfs2"
      resources:
        head:
          cpu: 18
          gpu: 0
          memory: 72Gi
          privileged: true
      limit: 12
    android_gym:
      quotagroup: "evobox_cpu_task"
      entrypoint: "bash /mnt/shared-storage-user/chenxinquan/AIEvoBox/env/androidgym/run.sh"
      volumes:
        - fsType: "mount.brainpp.cn/gpfs"
          endpoint: "gpfs://gpfs1/chenxinquan"
          containerPath: "/mnt/shared-storage-user/chenxinquan"
      limit: 1
    qa_gym:
      quotagroup: "evobox_proxy"
      entrypoint: >-
        bash -lc 'source /opt/openrt-venv/bin/activate &&
        python env/app.py'
      limit: 16
      volumes:
        - fsType: "mount.brainpp.cn/gpfs"
          endpoint: "gpfs://gpfs1/evobox-share"
          containerPath: "/mnt/shared-storage-user/evobox-share"

rayjob:
  domain: "https://h.pjlab.org.cn"
  tenant: "ailab"
  access_key: "0190c46827d4f2cd6632607bc1c2a0ca"
  secret_key: "8cf77e57dd77c977f4a59d43a507ebd1"
  token: ""
  verify: false                        # Whether to verify TLS certificates (set true in production)
  quotagroup: "evobox_cpu_task"        # Default quotagroup for all envs
  project: "ailab-evobox"              # Logical project name used on the RayJob platform
  description: "RL env Ray cluster"
